name: Build Andiodine
on: 
  workflow_dispatch:
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8
      - name: Execute Gradle build
        run: ./gradlew build
      - name: Archive build
        uses: actions/upload-artifact@v4
        with:
          name: apk-file
          path: build/outputs/apk/
